"""add target_region to advisories

Revision ID: 401a68250d59
Revises: b69eee4f02f3
Create Date: 2026-09-23 18:26:39.542523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '401a68250d59'
down_revision: Union[str, Sequence[str], None] = 'b69eee4f02f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advisories', sa.Column('target_region', sa.String(), server_default='All', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advisories', 'target_region')
    # ### end Alembic commands ###
