"""Add CropProfile model

Revision ID: 94a379504293
Revises: 7764aa810f3e
Create Date: 2026-09-23 10:59:31.703317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a379504293'
down_revision: Union[str, Sequence[str], None] = '7764aa810f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('sowing', 'flowering', 'pegging', 'podFill', 'harvesting', name='cropstage'), nullable=True),
    sa.Column('sowing_date', sa.DateTime(), nullable=True),
    sa.Column('health_good_pct', sa.Integer(), nullable=True),
    sa.Column('health_average_pct', sa.Integer(), nullable=True),
    sa.Column('health_poor_pct', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crop_profiles')
    # ### end Alembic commands ###
